### PR TITLE
Release 3.0.0

### PR DESCRIPTION
**Pull request by jdnichollsc**
### Added
- Added `hasBackButton` option to sets a back arrow instead of the default X icon to close the custom tab.
- Added default browser configuration for custom tab if any.
- Added `browserPackage` option to use a Package name of a browser to be used to handle Custom Tabs.
- Added `showInRecents` option to determine whether browsed website should be shown as separate entry in Android recents/multitasking view.

### Fixed
- Android `isAvailable` method checks **Custom Tab** support.
- Added a null check for `redirectResolve` in `safariViewControllerDidFinish`.
- Fixed `AppStateActiveOnce` event listener.
- Disable swipe to dismiss gesture for modal.

### CODE REVIEW

**Comment by wwelling** [comment]
@jdnichollsc I have begun testing/debugging this next release. I have corrected some minor lint errors and discovered the CI iOS builds are failing. Will report more when I find more.

**Comment by jdnichollsc** [comment]
Thanks for your help! Demo project is not working in my local environment and I don’t know why, also I need to debug these TODOs:
- https://github.com/proyecto26/nativescript-inappbrowser/pull/46/files#diff-7e96f7b14909450a876e532c2adc12455255bcc5d6c8f6ca3c503a32c947a47aR101
- https://github.com/proyecto26/nativescript-inappbrowser/pull/46/files#diff-7e96f7b14909450a876e532c2adc12455255bcc5d6c8f6ca3c503a32c947a47aR84

I don’t know if `!Application.android.paused` is the right way to detect is the app state is active **(The app is running in the foreground)**, what do you think? 🤔

**Comment by wwelling** [comment]
I am afraid you may be more knowledgeable in this regard than me. It may be possible to use an event listener and track state rather than depend on the paused property as an indication the app state is active.

https://docs.nativescript.org/core-concepts/application-lifecycle#android-activity-events

**Comment by wwelling** [comment]
On a good note, I have tested all the use cases I have. That is Facebook, LinkedIn, and Google on Android and iOS. The only failure, which existed before, is that on android API 27+ Google OAuth callback does not return back to the application. I am still trying to determine if this is Chrome blocking the redirect back or if the app is not activating its intent.

**Comment by jdnichollsc** [comment]
> I am afraid you may be more knowledgeable in this regard than me. It may be possible to use an event listener and track state rather than depend on the paused property as an indication the app state is active.
> 
> https://docs.nativescript.org/core-concepts/application-lifecycle#android-activity-events

Ohh yes, we're already using activity events here: https://github.com/proyecto26/nativescript-inappbrowser/blob/develop/src/utils.android.ts#L106

**Comment by jdnichollsc** [comment]
Ok, I removed TODOs, it's working as expected! I need help with the CI issue 😅

**Comment by wwelling** [comment]
> Ok, I removed TODOs, it's working as expected! <3 I need help with the CI issue 😅

This may work, #48

**Comment by wwelling** [comment]
@jdnichollsc let me know if there is anything else, in particular, I can review/test/debug.

**Comment by jdnichollsc** [comment]
Thanks a lot William for your help!

**Comment by wwelling** [comment]
Glad I can help.

**Comment by jdnichollsc** [comment]
Haha happy Halloween!

**Comment by bmacdonald** [comment]
@jdnichollsc Thank you for the work you put into this plugin!  Sorry it took so long for me to get back, I have been out of town.  Hopefully, I can work on the integration today.

Again, thank you for your time and effort.

**Pull request merged**
