### PR TITLE
chore: {N} 7 updates

### PR DESCRIPTION
**Pull request by NathanWalker**
```
cd src
npm run clean
npm run build
```

And you'll be all set.
Went ahead and bumped major version to 3.0.0 👍  - thank you for this plugin.

closes https://github.com/proyecto26/nativescript-inappbrowser/issues/39

### CODE REVIEW

**Comment by jdnichollsc** [comment]
Hello Nathan, let me try to publish a new version ASAP :)

**Comment by NathanWalker** [comment]
@jdnichollsc awesome - we should mention in readme that the usage is from:
```
import InAppBrowser from 'nativescript-inappbrowser';
```
to:
```
import { InAppBrowser } from 'nativescript-inappbrowser';
```
which gives a nice tree shakeable esm symbol. Would be a breaking change that we should mention.

**Comment by jdnichollsc** [comment]
But what're the advantages? I mean, can we avoid breaking changes in this case?

**Comment by NathanWalker** [comment]
Honestly everything with {N} 7 is moving to symbols like that due to advantages with tree shaking and es2015+ so I would recommend going with it like this. `import Thing` would generally be non standard with the stack's direction.

**Comment by jdnichollsc** [comment]
Oh ok, I need to modify the other library similar to this to maintain consistency. I'm busy until October 1st, so please wait mate :)

**Comment by aquinn637** [comment]
@jdnichollsc Any progress on this? I need this plugin for my project. :)

**Comment by lukasjuhas** [comment]
Thank you very much! Looking forward to having this in.

**Comment by bmacdonald** [comment]
> @jdnichollsc Any progress on this? I need this plugin for my project. :)

@aquinn637 I am in the same boat.  This is the only plugin preventing us from going to NativeScript 7.

**Comment by aquinn637** [comment]
@jdnichollsc @bmacdonald I made a temporary repository here: https://github.com/aquinn637/aquinn/tree/master/packages/inappbrowser
Of course, giving credit to the original author

**Comment by jdnichollsc** [comment]
There're new features in the next release, we're going to publish that this next weekend. I'm busy as I said before, thanks for your patience :)

**Comment by jdnichollsc** [comment]
Ok, checking about `tree shakeable esm symbol`

**Comment by jdnichollsc** [comment]
Ok, LGTM! Thanks for your help Nathan! I'm going to update **README** and add new changes before to publish this, let me confirm you tomorrow :)

**Comment by andreacappadona17** [comment]
Any updates on the release date for the plugin?

**Comment by jdnichollsc** [comment]
Today :)

**Comment by jdnichollsc** [comment]
Sorry folks, still working in some issues before to publish a new version (hope to finish that during this weekend), in the meantime please use this package

> @jdnichollsc @bmacdonald I made a temporary repository here: [https://github.com/aquinn637/aquinn/tree/master/packages/inappbrowser](https://github.com/aquinn637/aquinn/tree/master/packages/inappbrowser?rgh-link-date=2020-09-28T12%3A45%3A33Z)
> Of course, giving credit to the original author

**Comment by bmacdonald** [comment]
Is there an update on this plugin?

**Comment by jdnichollsc** [comment]
I'm planning to move these changes for this lib today, we're testing the changes :) https://github.com/proyecto26/react-native-inappbrowser/pull/195

**Comment by bmacdonald** [comment]
This is a critical plugin for us and is actually prevent us from porting to NativeScript 7.  We have a large enterprise grade application which requires this for SSO.  I see you have react-native-inappbrowser has been released.  However, is there a timeline to get the nativescript inappbrowser updated?

We have a small window to upgrade the framework due to the nature of enterprise developement.

We can't use @aquinn637 repo as it just throws can't resolve module errors.

**Comment by jdnichollsc** [comment]
I'm moving these fixes before to publish a new release, during the week is complicated for me (Because I'm not working with NativeScript, it's really just a hobby without sponsors), I'm trying to do that for this weekend :)

**Comment by aquinn637** [comment]
@jdnichollsc Thank you so much for this plugin. I'm in the same boat as @bmacdonald. You'll let us know when v3 is ready?

**Comment by jdnichollsc** [comment]
Hello folks, please help me to validate the next release here: https://github.com/proyecto26/nativescript-inappbrowser/pull/46

@NathanWalker I'm getting this error when I try to run the demo project:
```
Error while loading nativescript-cloud is: ENOENT: no such file or directory, scandir '/Users/jdnichollsc/.local/share/.nativescript-cli/extensions/node_modules'
Error while loading nativescript-starter-kits is: ENOENT: no such file or directory, scandir '/Users/jdnichollsc/.local/share/.nativescript-cli/extensions/node_modules'
No project found at or above '/Users/jdnichollsc/dev/nativescript/nativescript-inappbrowser/demo' and neither was a --path specified.
```

What do you think?
Thanks for your help! <3

**Comment by farfromrefug** [comment]
@jdnichollsc tried your demo and it works fine here.

**Comment by bmacdonald** [comment]
@jdnichollsc The demo for iOS and Android ran successfully.

I also published it to a private self-hosted npm repository to verify the import.

Thank you for the work you put in to this plugin!  We do appreciate it.

**Comment by jdnichollsc** [comment]
ohh do you know if we need to update nativescript cli? also CI iOS builds are failing 🤔

**Comment by bmacdonald** [comment]
I would.  Everything I tested under is using NS CLI 7.0.11.

**Comment by jdnichollsc** [comment]
We can continue the discussion here https://github.com/proyecto26/nativescript-inappbrowser/pull/46, thanks a lot for your help! <3

**Comment by jdnichollsc** [comment]
Check the new version, thanks for your amazing help guys! ❤️

**Pull request merged**
