### PR TITLE
feat(android): support metadata filtering

### PR DESCRIPTION
**Pull request by farfromrefug**
For android platform for now

### CODE REVIEW

**Comment by jdnichollsc** [comment]
Hello mate, please open an issue discussing what this is and follow the PR template.

**Comment by farfromrefug** [comment]
An issue for what ? 
Sorry about the template. 
You can know everything about metadata filtering here https://docs.nativescript.org/advanced-concepts.html#metadata-filtering

**Comment by jdnichollsc** [comment]
We use the issue for our CHANGELOG.md file, thanks for your collaboration! <3

**Comment by farfromrefug** [comment]
@jdnichollsc i changed the title so it can be used in changelog.

**Comment by jdnichollsc** [comment]
You haven't discussed with any maintainers. I'll close this issue in the meantime, thanks for understanding 👍

**Comment by farfromrefug** [comment]
Well nice makes you want to contribute :)

**Comment by jdnichollsc** [comment]
Hello mate, I recognize that this is a valuable improvement for this library, but discussing about the changes you want to introduce from an issue is part of the [Contribution Guidelines](https://github.com/proyecto26/nativescript-inappbrowser/blob/develop/CONTRIBUTING.md#contributing) of this project.

That being said, when you're contributing to Open Source you operate as part of a team, you're a team player by having the proper dialog with the project's active maintainers first, so please show the respect of following the guidelines in opening an issue when required and properly communicate with the maintainers of project 🙂

Have a great day,
Juan

**Comment by farfromrefug** [comment]
Honestly we have different view on colaboration in oss projects. I never and will.never refuse a PR from anyone because they did not open an issue or put a wrong title.
If i did nativescript-community would have no PR :)
I understand your way and we had that discussion about you wanting to.maintain your plugin here for promotion reasons and i understand that.
Just makes me feel sorry and a bit sad. Hard to keep using a plugin which refuses contributions so easily. I wanted to make more PRs to improve performances. Will have to fork and i feel really sad about. I wont do it nativescript-community though as it would feel like a lack of respect.
Thank you

**Comment by jdnichollsc** [comment]
Contributing to OSS is not an easy thing, this requires time from others to review your changes, debug your code and then generate a new release with a good explanation of the changes that were introduced in that new version.
Having a simple discussion to explain why that change is necessary is part of a good process, I spent time creating these guidelines and templates to have better traceability of the project, so if you can give a bit of context it would be greatly appreciated, any issue and pull requests are always welcome! 🙂

**Pull request closed without merging**
